export const ErrorCodeEnum = Object.freeze({
  /* ================= AUTH ================= */
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_TOKEN_NOT_FOUND: "AUTH_TOKEN_NOT_FOUND",
  AUTH_UNAUTHORIZED_ACCESS: "AUTH_UNAUTHORIZED_ACCESS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_ALREADY_EXISTS: "AUTH_EMAIL_ALREADY_EXISTS",
  AUTH_TOO_MANY_ATTEMPTS: "AUTH_TOO_MANY_ATTEMPTS",

  /* ================= ACCESS / RBAC ================= */
  ACCESS_UNAUTHORIZED: "ACCESS_UNAUTHORIZED",
  ACCESS_PERMISSION_DENIED: "ACCESS_PERMISSION_DENIED",
  WORKSPACE_CONTEXT_MISSING: "WORKSPACE_CONTEXT_MISSING",
  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",

  /* ================= VALIDATION ================= */
  VALIDATION_ERROR: "VALIDATION_ERROR",

  /* ================= RESOURCES ================= */
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  /* ================= SYSTEM ================= */
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
});
